name: example
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
    
  cupertino_icons: ^1.0.6
  flutter_colorpicker: ^1.1.0
  css:
    git:
      url: https://github.com/Knightro63/css.git
  three_js: ^0.2.5
    #path: ../packages/three_js
  three_js_helpers: ^0.2.3
  three_js_transform_controls: ^0.2.1
  three_js_svg: ^0.2.1
  three_js_objects: ^0.2.1
  three_js_tjs_loader: ^0.2.1
  three_js_postprocessing: ^0.2.1
  three_js_modifers: ^0.2.1
  three_js_terrain: ^0.2.0
  three_js_exporters: ^0.2.0
  three_js_line: ^0.2.1
  three_js_bvh_csg: ^0.2.0
  three_js_video_texture: ^0.0.2
  three_js_audio: ^0.2.1
  three_js_audio_latency: ^0.0.1
  three_js_advanced_exporters: ^0.0.1

  permission_handler: ^11.3.1
  camera: ^0.10.6
  camera_macos: ^0.0.9
  # camera_linux: ^0.0.8
  # camera_windows: ^0.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

dependency_overrides:
  permission_handler_apple:
    git:
      url: https://github.com/alex-melnyk/flutter-permission-handler.git 
      path: permission_handler_apple
  file_picker: ^10.1.9
  three_js_advanced_loaders:
    path: ../packages/three_js_advanced_loaders
  three_js_animations:
    path: ../packages/three_js_animations
  three_js_math:
    path: ../packages/three_js_math
  three_js_core:
    path: ../packages/three_js_core
  three_js_core_loaders:
    path: ../packages/three_js_core_loaders
  flutter_angle:
    path: ../../flutter_angle/flutter_angle
    
flutter:
  uses-material-design: true
  assets:
    - assets/pingfang.ttf
    - assets/helvetiker_bold.typeface.json
    - assets/screenshots/
    - assets/models/bvh/
    - assets/models/obj/cerberus/
    - assets/models/obj/male02/
    - assets/models/obj/
    - assets/models/json/
    - assets/models/gcode/
    - assets/models/ply/binary/
    - assets/models/ply/ascii/
    - assets/models/stl/binary/
    - assets/models/stl/ascii/
    - assets/models/vox/
    - assets/models/usdz/
    - assets/models/xyz/
    - assets/models/collada/
    - assets/models/collada/stormtrooper/
    - assets/models/collada/elf/
    - assets/models/md2/ogro/
    - assets/models/md2/ogro/skins/
    - assets/models/md2/ratamahatta/
    - assets/models/md2/ratamahatta/skins/
    - assets/models/pcd/ascii/
    - assets/models/pcd/binary/
    - assets/models/pcd/binary_compressed/
    - assets/models/gltf/test/
    - assets/models/gltf/
    - assets/models/gltf/test/
    - assets/models/gltf/flutter/
    - assets/models/gltf/Flower/
    - assets/models/gltf/LeePerrySmith/
    - assets/models/gltf/RobotExpressive/
    - assets/models/gltf/DamagedHelmet/glTF/
    - assets/models/gltf/AnimatedMorphSphere/glTF/
    - assets/models/gltf/ShaderBall2/
    - assets/models/gltf/ferrari/
    - assets/models/gltf/Soldier/
    - assets/models/gltf/Dungon_Warkarma/
    - assets/models/svg/
    - assets/models/fbx/
    - assets/textures/
    - assets/textures/lava/
    - assets/textures/lensflare/
    - assets/textures/equirectangular/
    - assets/textures/terrain/
    - assets/textures/sprites/
    - assets/textures/planets/
    - assets/textures/decal/
    - assets/textures/cube/Park2/
    - assets/textures/cube/pisa/
    - assets/textures/three_terrain/
    - assets/textures/water/
    - assets/textures/floors/
    - assets/sounds/